Raise rust-version of autocargo projects to support 2024 edition
Summary:
This unblocks {D75799054}. Without this diff, Cargo reports a contradiction.

```lang=log,counterexample
Error: While running 'generate_cargo_lock' for 'scm/dotslash/oss'

Caused by:
    0: failed to parse manifest at `/data/users/dtolnay/fbsource/fbcode/scm/dotslash/oss/Cargo.toml`
    1: rust-version 1.83 is older than first version (1.85.0) required by the specified edition (2024)
```

Reviewed By: ejnguyen

Differential Revision: D75799055

fbshipit-source-id: f5afc82f484af38fb5d768924e51788e001d3894